spring.application.name=etl1

spring.datasource.url=jdbc:postgresql://localhost:5432/etl1db
spring.datasource.username=nattspeight
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


name: color-scraper

jpa:
hibernate:
ddl-auto: update
show-sql: true

thymeleaf:
cache: false

scraper:
delay-seconds: 60

logging:
level:
com.example.colorscraper: DEBUG