spring.application.name=etl1

spring.datasource.url=jdbc:postgresql://localhost:5432/etl1db
spring.datasource.username=nattspeight
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

scraper.delay-seconds=60

logging.level.com.example.etl1=DEBUG
